#!/bin/sh

echo "Switching to branch master"
git checkout master

echo "Building app"
npm run build

echo "Deploying files to server"
rsync -a ./dist/ root@143.42.22.189:/var/www/citycenter.mk/
echo "Deployment complete"
