export const APARTMENTS = [
  {
    id: 1,
    type: "Studio Apartment",
    name: "City Center Studio",
    img: "/224807587.jpg",
    price: 27,
    size: 21,
    beds: 1,
    persons: "1-2",
    link: "https://www.booking.com/Share-nZIwmH",
  },
  {
    id: 2,
    type: "One Bedroom Apartment",
    name: "City Center Apartments",
    img: "/268372157.jpg",
    price: 29,
    size: 40,
    beds: 1,
    persons: "1-3",
    link: "https://www.booking.com/Share-nZIwmH",
  },
  {
    id: 3,
    type: "Two Bedroom Apartment",
    name: "City Center Apartments",
    img: "/268371833.jpg",
    price: 27,
    size: 21,
    beds: 1,
    persons: "1-2",
    link: "https://www.booking.com/Share-nZIwmH",
  },
  {
    id: 4,
    type: "Large Apartment",
    name: "City Center Apartments",
    img: "/208336563.jpg",
    price: 27,
    size: 21,
    beds: 1,
    persons: "1-2",
    link: "https://www.booking.com/Share-nZIwmH",
  },
  {
    id: 5,
    type: "Medium Apartment",
    name: "City Center Apartments",
    img: "/208336324.jpg",
    price: 27,
    size: 21,
    beds: 1,
    persons: "1-2",
    link: "https://www.booking.com/Share-nZIwmH",
  },
  {
    id: 6,
    type: "Studio Apartment",
    name: "City Apartment",
    img: "/150317299.jpg",
    price: 27,
    size: 21,
    beds: 1,
    persons: "1-2",
    link: "https://www.booking.com/hotel/mk/city-apartment-strumica.en-gb.html?aid=356980&label=gog235jc-1DCAsokwFCF2NpdHktYXBhcnRtZW50LXN0cnVtaWNhSDNYA2iTAYgBAZgBCbgBB8gBDdgBA-gBAYgCAagCA7gCrdueowbAAgHSAiQwM2IzYmUxMy1iOGNhLTQ2MTEtYjE5Zi0xOTc1NDAzYWVhOGHYAgTgAgE&sid=242985017477781fe28043f0c547c400&dist=0&group_adults=2&group_children=0&keep_landing=1&no_rooms=1&sb_price_type=total&type=total&",
  },
];
