export const ATTRACTIONS_DATA = [
  {
    id: 1,
    type: "Nature",
    title: "Koleshino Waterfalls",
    desc: "Flowing from the Baba River, the waterfall is found at an elevation of 610 metres on the Mount Belasica.",
    img: "/koleshino.jpg",
    alt: "image of Koleshino Waterfalls",
    km: "20.9",
    link: "#",
    maps: "#",
  },
  {
    id: 2,
    type: "Nature",
    title: "Belasica Mountain",
    desc: "Flowing from the Baba River, the waterfall is found at an elevation of 610 metres on the Mount Belasica.",
    img: "/belasica.jpeg",
    alt: "image of Belasica Mountain",
    km: "50.1",
    link: "#",
    maps: "#",
  },
  {
    id: 3,
    type: "Religion",
    title: "Holy Mother of God Eleusa",
    desc: "Flowing from the Baba River, the waterfall is found at an elevation of 610 metres on the Mount Belasica.",
    img: "/holymother.jpg",
    alt: "image of the church",
    km: "9.6",
    link: "#",
    maps: "#",
  },
  {
    id: 4,
    type: "History",
    title: "Tzarevi Kuli",
    desc: "Flowing from the Baba River, the waterfall is found at an elevation of 610 metres on the Mount Belasica.",
    img: "/tzar.jpg",
    alt: "image of the fortress",
    km: "9.6",
    link: "#",
    maps: "#",
  },
];
